# Generated by Django 2.2.5 on 2019-09-28 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('companyid', models.CharField(max_length=50, verbose_name='company id')),
                ('website', models.CharField(db_index=True, max_length=200, verbose_name='website')),
            ],
            options={
                'verbose_name': 'Courriers',
                'verbose_name_plural': 'Courrier',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryDate', models.DateField(blank=True, null=True, verbose_name='delivery date')),
                ('invoiceData', models.CharField(db_index=True, max_length=200, verbose_name='invoice data')),
                ('description', models.TextField(blank=True, default='', max_length=2000, verbose_name='description')),
                ('address', models.CharField(db_index=True, max_length=200, verbose_name='address')),
                ('estimateData', models.DateField(blank=True, null=True, verbose_name='estimate data')),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_courrier', to='deliveries.Courrier')),
            ],
            options={
                'verbose_name': 'Deliverys',
                'verbose_name_plural': 'Delivery',
            },
        ),
    ]
